# Generated by Django 5.0.9 on 2024-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schedule_end_time_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(max_length=400, null="User hasn't provided an introduction!"),
            preserve_default="User hasn't provided an introduction!",
        ),
    ]
